library (ISLR)
attach(Wage)
head(Wage)
names(Wage)
summary(Wage)
fit =lm(wage~poly(age,4), data=Wage)
summary(fit)
coef(summary(fit))
fit2 =lm(wage~poly(age,4, raw=T), data=Wage)
summary(fit2)
fit2a = lm(wage~age+I(age^2)+I(age^3)+I(age^4), data=Wage)
coef(fit2a)
agelims = range(age)
age.grid = seq(from = agelims[1], to=agelims[2])
preds = predict(fit, newdata = list(age=age.grid), se=T)
se.bands =cbind(preds$fit + 2*preds$se.fit, 
                preds$fit - 2*preds$se.fit)
par(mfrow=c(1,2), mar=c(4.5,4.5,1,1), oma=c(0,0,4,0))
plot(age,wage,xlim=agelims,cex=.5,col="darkgrey")
title("Degree-4 Polynomial",outer=T)
lines(age.grid,preds$fit,lwd=2,col="blue")
matlines(age.grid,se.bands,lwd=1,col="blue",lty=3)
### anova testing
fit.1 = lm(wage~age, data=Wage)
fit.2 = lm(wage~poly(age,2,raw=T), data=Wage)
fit.3 = lm(wage~poly(age,3,raw=T), data=Wage)
fit.4 = lm(wage~poly(age,4,raw=T), data=Wage)
fit.5 = lm(wage~poly(age,5,raw=T), data=Wage)
anova(fit.1,fit.2,fit.3,fit.4,fit.5)## more than 2 models...
fit.1=lm(wage~education+age,data=Wage)
fit.2=lm(wage~education+poly(age,2),data=Wage)
fit.3=lm(wage~education+poly(age,3),data=Wage)
anova(fit.1,fit.2,fit.3)
####
fit=glm(I(wage>250)~poly(age,4), data=Wage, family=binomial)
preds = predict (fit, newdata=list(age=age.grid),se=T)
pfit = exp(preds$fit)/(1+exp(pred$fit))
#se.bands.logit = cbind(preds$fit+2*)
plot(age,wage,xlim=agelims, cex=.5,col="darkgrey")
title("Local Regression")
fit = loess(wage~age, span=.2, data=Wage)
fit2=loess(wage~age,span=.5,data=Wage)
lines(age.grid, predict(fit, data.frame(age=age.grid)),col="red",lwd=2)
lines(age.grid, predict(fit2, data.frame(age=age.grid)),col="red",lwd=2)
legend("topright",legend=c("Span=0.2","Span=0.5",
                           col=c("red","blue"),lty=1,lwd=2,ce))